#!/bin/bash
###########################################################
#Script Auto Install Apache, PHP 8.1, MariaDB, phpmyadmin,FFMPEG,TRANSMISSION,OPENVPN,LETSENCRYPT
#Author      :  MAVEN
#Instagram   :  https://www.kalixhosting.com
#Version     :  1.0.1
#Date        :  04/02/2024
#OS          :  ALMALINUX
###########################################################

echo "Auto Install LAMP ALMALINUX"
echo "###########################"

# Update ALMALINUX
sudo setenforce 0
yum -y update
yum -y install wget
yum -y upgrade
yum install wget nano zip unzip -y
chmod +rw /root
chmod 777 /root
yum -y install epel-release
yum -y update

# Install transmission
yum -y install transmission-cli transmission-common transmission-daemon
systemctl start transmission-daemon.service

# EPEL Repo
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
yum -y install yum-utils

# Install MariaDB
yum -y install mariadb-server mariadb
systemctl start mariadb.service
systemctl enable mariadb.service

# Install Apache
yum -y install httpd
systemctl start httpd.service
systemctl enable httpd.service

# Firewall settings
yum -y install firewalld
systemctl enable --now firewalld
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload

# Install PHP 8.1 and extensions
yum -y install php php-{cli,common,fpm,curl,gd,mbstring,process,snmp,xml,zip,memcached,mysqlnd,json,mbstring,pdo,pdo-dblib,xml}

systemctl restart httpd.service

echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php

# MariaDB Support PHP
yum -y install mariadb-server
systemctl start mysql.service
systemctl enable mariadb
systemctl start mariadb
systemctl restart httpd.service

# Install PHPMyAdmin
wget https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-all-languages.zip
unzip phpMyAdmin-5.0.1-all-languages.zip
mv phpMyAdmin-5.0.1-all-languages /usr/share/phpmyadmin
mkdir /usr/share/phpmyadmin/tmp
chown -R apache:apache /usr/share/phpmyadmin
chmod 777 /usr/share/phpmyadmin/tmp

# Config PHPMyAdmin
mv /etc/httpd/conf.d/phpmyadmin.conf /etc/httpd/conf.d/phpMyadmin.conf.backup
wget https://raw.githubusercontent.com/KALIXHOSTING/ALMALINUXLAMPAUTOINSTALL/main/phpmyadmin.conf
cp phpmyadmin.conf /etc/httpd/conf.d/

echo "Do you want to change the MariaDB root password? (y/n)"
read changepass

case $changepass in
    y|Y)
        mysql_secure_installation
        ;;
    n|N)
        ;;
    *)
        echo "Invalid input. Skipping password change."
        ;;
esac

# Restart Apache
systemctl restart httpd.service

# Install Certbot
yum -y install certbot python3-certbot-apache mod_ssl

# Install btop
yum -y install epel-release
yum -y install btop

# Install Perl
yum -y install perl-CGI perl-libwww-perl perl-DBI perl-DBD-MySQL perl-GD perl-Cache-Memcached perl-Digest-SHA perl-LWP-Protocol-https

# CHMOD VAR/WWW/HTML
chmod +rw /var
chmod +rw /var/www/html
chmod 777 /var
chmod 777 /var/www/html
chmod +rw /var/www/cgi-bin
chmod 777 /var/www/cgi-bin

# Restart Apache
systemctl restart httpd.service

# Install FFMPEG
yum -y install epel-release
yum -y localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
yum -y install ffmpeg ffmpeg-devel

# Install OpenVPN
wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh

echo "######## KALIXHOSTING AUTOINSTALL FOR ALMALINUX | FINISH #########"
